import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

interface Author {
  name: string;
  url: string;
}

export const metadata: Metadata = {
  title: "Sellie",
  description: "Generated by create next app",
  authors: [
    {
      name: "Fredy Antonio Almeyda Alania",
      url: "https://github.com/Fredy002",
    }
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
